version: '3.8'
services:
  app:
    build: ./
    volumes:
      - ./node:/app
      - /app/node_modules
    expose:
      - '3000'
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: fullcycle
    platform: linux/amd64
    command: sh -c 'while ! nc -z db 3306; do sleep 1; done; npm start'
    networks:
      - node_nginx_net

  db:
    platform: linux/amd64
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fullcycle
    volumes:
      - 'db-data:/var/lib/mysql'
      - './mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    networks:
      - node_nginx_net

  nginx:
    image: 'nginx:latest'
    restart: always
    platform: linux/amd64
    ports:
      - '8080:80'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - app
    networks:
      - node_nginx_net

networks:
  node_nginx_net:
    driver: bridge

volumes:
  db-data: null
